# CSV

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("world-data-2023.csv")

In [3]:
df.head()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887

In [6]:
df['Population'] = df['Population'].replace(',','',regex=True).fillna('0').astype(int)

In [10]:
new_df = df[df['Population'] > 50000000]

In [11]:
new_df

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
13,Bangladesh,"1,265",BD,70.60%,"148,460","221,000",18.18,880.0,Dhaka,"84,246",...,71.80%,0.58,167310838,59.00%,8.80%,33.40%,4.19%,"60,987,417",23.684994,90.356331
23,Brazil,25,BR,33.90%,"8,515,770","730,000",13.92,55.0,Brasï¿½ï¿½ï¿½,"462,299",...,28.30%,2.15,212559417,63.90%,14.20%,65.10%,12.08%,"183,241,641",-14.235004,-51.925280
36,China,153,CN,56.20%,"9,596,960","2,695,000",10.90,86.0,Beijing,"9,893,038",...,32.40%,1.98,1397715000,68.00%,9.40%,59.20%,4.32%,"842,933,962",35.861660,104.195397
37,Colombia,46,CO,40.30%,"1,138,910","481,000",14.88,57.0,Bogotï¿½,"97,814",...,18.30%,2.18,50339443,68.80%,14.40%,71.20%,9.71%,"40,827,302",4.570868,-74.297333
45,Democratic Republic of the Congo,40,CD,11.60%,"2,344,858","134,000",41.18,243.0,Kinshasa,"2,021",...,37.40%,0.07,86790567,63.50%,10.70%,50.70%,4.24%,"39,095,679",-4.038333,21.758664
51,Egypt,103,EG,3.80%,"1,001,450","836,000",26.38,20.0,Cairo,"238,560",...,62.00%,0.45,100388073,46.40%,12.50%,44.40%,10.76%,"42,895,824",26.820553,30.802498
57,Ethiopia,115,ET,36.30%,"1,104,300","138,000",32.34,251.0,Addis Ababa,"14,870",...,37.80%,0.08,112078730,79.60%,7.50%,37.70%,2.08%,"23,788,710",9.145000,40.489673
60,France,119,FR,52.40%,"643,801","307,000",11.30,33.0,Paris,"303,276",...,6.80%,3.27,67059887,55.10%,24.20%,60.70%,8.43%,"54,123,364",46.227638,2.213749
64,Germany,240,DE,47.70%,"357,022","180,000",9.50,49.0,Berlin,"727,973",...,12.50%,4.25,83132799,60.80%,11.50%,48.80%,3.04%,"64,324,835",51.165691,10.451526
77,India,464,IN,60.40%,"3,287,263","3,031,000",17.86,91.0,New Delhi,"2,407,672",...,65.10%,0.86,1366417754,49.30%,11.20%,49.70%,5.36%,"471,031,528",20.593684,78.962880
78,Indonesia,151,ID,31.50%,"1,904,569","676,000",18.07,62.0,Jakarta,"563,325",...,48.30%,0.43,270203917,67.50%,10.20%,30.10%,4.69%,"151,509,724",-0.789275,113.921327
79,Iran,52,IR,28.20%,"1,648,195","563,000",18.78,98.0,Tehran,"661,710",...,39.70%,1.58,82913906,44.70%,7.40%,44.70%,11.38%,"62,509,623",32.427908,53.688046
83,Italy,206,IT,43.20%,"301,340","347,000",7.30,39.0,Rome,"320,411",...,22.80%,3.98,60297396,49.60%,24.30%,59.10%,9.89%,"42,651,966",41.871940,12.567380
85,Japan,347,JP,12.30%,"377,944","261,000",7.40,81.0,Tokyo,"1,135,886",...,13.10%,2.41,126226568,61.70%,11.90%,46.70%,2.29%,"115,782,416",36.204824,138.252924
88,Kenya,94,KE,48.50%,"580,367","29,000",28.75,254.0,Nairobi,"17,910",...,33.40%,0.16,52573973,74.70%,15.10%,37.20%,2.64%,"14,461,523",-0.023559,37.906193
110,Mexico,66,MX,54.60%,"1,964,375","336,000",17.60,52.0,Mexico City,"486,406",...,41.40%,2.38,126014024,60.70%,13.10%,55.10%,3.42%,"102,626,859",23.634501,-102.552784
118,Myanmar,83,MM,19.50%,"676,578","513,000",17.55,95.0,Naypyidaw,"25,280",...,73.90%,0.68,54045420,61.70%,5.40%,31.20%,1.58%,"16,674,093",21.916221,95.955974
126,Nigeria,226,NG,77.70%,"923,768","215,000",37.91,234.0,Abuja,"120,369",...,72.20%,0.38,200963599,52.90%,1.50%,34.80%,8.10%,"102,806,948",9.081999,8.675277
131,Pakistan,287,PK,47.80%,"796,095","936,000",28.25,92.0,Islamabad,"201,150",...,66.50%,0.98,216565318,52.60%,9.20%,33.90%,4.45%,"79,927,762",30.375321,69.345116
138,Philippines,368,PH,41.70%,"300,000","153,000",20.55,63.0,Manila,"122,287",...,53.50%,0.60,108116615,59.60%,14.00%,43.10%,2.15%,"50,975,903",12.879721,121.774017
143,Russia,9,RU,13.30%,"17,098,240","1,454,000",11.50,7.0,Moscow,"1,732,027",...,36.40%,4.01,144373535,61.80%,11.40%,46.20%,4.59%,"107,683,889",61.524010,105.318756
161,South Africa,49,ZA,79.80%,"1,219,090","80,000",20.51,27.0,Pretoria,"476,644",...,7.70%,0.91,58558270,56.00%,27.50%,29.20%,28.18%,"39,149,717",-30.559482,22.937506
162,South Korea,527,KR,17.40%,"99,720","634,000",6.40,82.0,Seoul,"620,302",...,36.80%,2.36,51709098,63.00%,15.60%,33.20%,4.15%,"42,106,719",35.907757,127.766922
172,Tanzania,67,TZ,44.80%,"947,300","28,000",36.70,255.0,Dodoma,"11,973",...,26.10%,0.01,58005463,83.40%,11.50%,43.80%,1.98%,"20,011,885",-6.369028,34.888822
173,Thailand,137,TH,43.30%,"513,120","455,000",10.34,66.0,Bangkok,"283,763",...,11.80%,0.81,69625582,67.30%,14.90%,29.50%,0.75%,"35,294,600",15.870032,100.992541
179,Turkey,110,TR,49.80%,"783,562","512,000",16.03,90.0,Ankara,"372,725",...,16.90%,1.85,83429615,52.80%,17.90%,42.30%,13.49%,"63,097,818",38.963745,35.243322
185,United Kingdom,281,GB,71.70%,"243,610","148,000",11.00,44.0,London,"379,025",...,14.80%,2.81,66834405,62.80%,25.50%,30.60%,3.85%,"55,908,316",55.378051,-3.435973
186,United States,36,US,44.40%,"9,833,517","1,359,000",11.60,1.0,"Washington, D.C.","5,006,302",...,11.10%,2.61,328239523,62.00%,9.60%,36.60%,14.70%,"270,663,028",37.090240,-95.712891
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",...,43.50%,0.82,96462106,77.40%,19.10%,37.60%,2.01%,"35,332,140",14.058324,108.277199

In [14]:
new_df.to_csv('result.csv', index_label='index', sep=';')

# XLSX

In [16]:
df = pd.read_excel('world-data-2023.xlsx')

In [17]:
df.head()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
0,Afghanistan,60.0,AF,58.10%,652.23,323,32.49,93.0,Kabul,8.672,...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
1,Albania,105.0,AL,43.10%,28.748,9,11.78,355.0,Tirana,4.536,...,56.90%,2023-02-01 00:00:00,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331
2,Algeria,18.0,DZ,17.40%,"2,381,741",317,24.28,213.0,Algiers,150.006,...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626
3,Andorra,164.0,AD,40.00%,468,NaN,2023-02-07 00:00:00,376.0,Andorra la Vella,469,...,36.40%,3.33,77.142,NaN,NaN,NaN,NaN,67.873,42.506285,1.521801
4,Angola,26.0,AO,47.50%,"1,246,700",117,40.73,244.0,Luanda,34.693,...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887

bad data?

### I have no sheets for practising `sheet_name='name'`